
name: ${MraJscEadLboM307}
networks:
  default:
    name: ${MraJscEadLboM307}
    driver: bridge

services:
  server:
    container_name: ${MraJscEadLboM307}-web
    extra_hosts:
      host.docker.internal: host-gateway  
    build:
      context: .
    restart: no
    ports: ["9080:80"]
    volumes:
      - ../htdocs/:/var/www/html
      - ../logs/:/var/www/logs
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

  db:
    container_name: ${MraJscEadLboM307}-db

    image: mariadb
    volumes: ["./db/:/var/lib/mysql:Z"]
    restart: no
    ports: ["9306:3306"]
    environment:
      MARIADB_ROOT_PASSWORD: ${HilfeLol2026!}

  adminer:
    container_name: ${MraJscEadLboM307}-adminer

    image: adminer
    restart: no
    ports: ["9081:8080"]
